-- 자동차 평균 대여 기간 구하기
SELECT CAR_ID, ROUND(AVG((DATEDIFF(END_DATE, START_DATE) + 1)), 1) AS "AVERAGE_DURATION"
FROM car_rental_company_rental_history
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7.0
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;