-- 분기별 분화된 대장균의 개체 수 구하기
SELECT IF(MONTH(DIFFERENTIATION_DATE) <= 3, "1Q", 
          IF(MONTH(DIFFERENTIATION_DATE) <= 6, "2Q", 
             IF(MONTH(DIFFERENTIATION_DATE) <= 9, "3Q", "4Q"))) AS "QUARTER", COUNT(*) AS "ECOLI_COUNT"
FROM ecoli_data
GROUP BY QUARTER
ORDER BY QUARTER;