-- 물고기 종류 별 대어 찾기
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO f 
INNER JOIN FISH_NAME_INFO fn ON f.FISH_TYPE = fn.FISH_TYPE
WHERE (f.FISH_TYPE, LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY ID;