-- 입양 시각 구하기(1)
SELECT DATE_FORMAT(DATETIME, "%k") AS "HOUR", COUNT(*) AS "COUNT"
FROM animal_outs
WHERE DATE_FORMAT(DATETIME, "%k") >= 9 AND DATE_FORMAT(DATETIME, "%k") < 20
GROUP BY DATE_FORMAT(DATETIME, "%k")
ORDER BY DATE_FORMAT(DATETIME, "%H");