-- 저자 별 카테고리 별 매출액 집계하기
SELECT b.AUTHOR_ID AS AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(price * sales) AS TOTAL_SALES
FROM book b
INNER JOIN book_sales s ON b.BOOK_ID = s.BOOK_ID
INNER JOIN author a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;