-- 특정 조건을 만족하는 물고기별 수와 최대 길이 구하기
SELECT COUNT(*) AS "FISH_COUNT", MAX(LENGTH) AS "MAX_LENGTH", FISH_TYPE
FROM fish_info
GROUP BY FISH_TYPE
HAVING AVG(IF(LENGTH >= 10, LENGTH, 10)) >= 33
ORDER BY FISH_TYPE;