-- 업그레이드 된 아이템 구하기
SELECT ii.ITEM_ID AS "ITEM_ID", ii.ITEM_NAME AS "ITEM_NAME", ii.RARITY AS "RARITY"
FROM item_info ii 
LEFT OUTER JOIN item_tree it ON ii.ITEM_ID = it.ITEM_ID
WHERE it.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM item_info WHERE RARITY = "RARE")
ORDER BY it.ITEM_ID DESC;