-- 특정 형질을 가지는 대장균 찾기
SELECT COUNT(*) AS COUNT
FROM ecoli_data
WHERE NOT SUBSTRING(CONV(GENOTYPE, 10, 2), -2, 1) = "1" 
      AND (SUBSTRING(CONV(GENOTYPE, 10, 2), -1, 1) = "1" OR SUBSTRING(CONV(GENOTYPE, 10, 2), -3, 1) = "1");