-- 서울에 위치한 식당 목록 출력하기
-- 리뷰가 없는 음식점은 제외
SELECT ri.REST_ID AS REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, 
       ADDRESS, 
       ROUND(AVG(IF(REVIEW_SCORE IS NOT NULL, REVIEW_SCORE, 0.00)), 2) AS SCORE
FROM rest_info ri
RIGHT JOIN rest_review rr ON ri.REST_ID = rr.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;